name: TempceLib
version: '1.0.0'
main: com.Tempce.tempceLib.TempceLib
api-version: '1.20'
author: Tempce
description: 包括的なMinecraftプラグイン開発支援ライブラリ

commands:
  tempce:
    description: TempceLibのメイン コマンド
    usage: /tempce <subcommand>
    aliases: [tclib, tempcelib]
    permission: tempcelib.use
    permission-message: "§cTempceLibを使用する権限がありません"

permissions:
  tempcelib.use:
    description: TempceLibの基本機能を使用
    default: true
  tempcelib.admin:
    description: TempceLibの管理機能を使用
    default: op
